Eshop/Eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Eshop/main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='homePage'),
    path('category-list/',views.category_list,name='category_listPage'),
    path('brand/',views.brand_list,name='brand_listPage'),
    path('product/',views.product_list,name='product_listPage'),
    path('category-product-list/<int:cat_id>/',views.category_product_list,name='category_product_listPage'),
    path('brand-product-list/<int:brand_id>/',views.brand_product_list,name='brand_product_listPage'),
    path('product-detail/<str:slug>/<int:id>/',views.product_detail,name='product_detailPage'),
    path('search/',views.search,name='searchPage'),
    path('filter-data/',views.filter_data,name='filter-data'),


]

Eshop/main/models.py
from django.db import models
from django.utils.html import mark_safe


# Create your models here.
class Baner(models.Model):
    img=models.ImageField(upload_to='baners/')
    alt_img=models.CharField(max_length=100)

    class Meta:
        verbose_name_plural='1. Baners'

    def __str__(self):
        return self.alt_img

class Category(models.Model):
    title=models.CharField(max_length=100)
    image=models.ImageField(upload_to='categeries/',null=True,blank=True) 
    class Meta:
        verbose_name_plural='2. Categories'

    def image_tag(self):
        if self.image:
            return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
        return 'No Image Found'

        
    def __str__(self):
        return self.title
    
class Brand(models.Model):
    title=models.CharField(max_length=100)
    image=models.ImageField(upload_to='brands/',null=True,blank=True) 
    class Meta:
        verbose_name_plural='3. Brands'

    def image_tag(self):
            if self.image:
                return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
            return 'No Image Found'
           
    
    def __str__(self):
        return self.title
    
class Color(models.Model):
    title=models.CharField(max_length=100)
    color_code=models.CharField(max_length=100)
    class Meta:
        verbose_name_plural='4. Colors'
    def color_bg(self):
            return mark_safe('<div style="width:50px; height:50px; background-color:%s"></div>' % (self.color_code))

    def __str__(self):
        return self.title
class Size(models.Model):
    title=models.CharField(max_length=100 ,null=True,blank=True)

    class Meta:
        verbose_name_plural='5. Sizes'
    def __str__(self):
        return self.title
    
class Product(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField(max_length=100)
    details=models.TextField()
    spec=models.TextField()
    brand=models.ForeignKey(Brand,on_delete=models.CASCADE)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    color=models.ForeignKey(Color,on_delete=models.CASCADE)
    size=models.ForeignKey(Size,on_delete=models.CASCADE)
    status=models.BooleanField(default=True)
    is_featured=models.BooleanField(default=False)

    class Meta:
        verbose_name_plural='6. Products'

   # def image_tag(self):
          #  return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title
    
#product Attribute
class ProductAttribute(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    color=models.ForeignKey(Color,on_delete=models.CASCADE)
    size=models.ForeignKey(Size,on_delete=models.CASCADE, null=True, blank=True)
    price=models.PositiveIntegerField()
    image=models.ImageField(upload_to='products/',null=True)
    class Meta:
        verbose_name_plural='7. ProductAttributes'
        unique_together = ('product', 'color', 'size')

    def __str__(self):
        return self.product.title
    
    def image_tag(self):
            if self.image:
                return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
            return 'No Image Found'
    

    
    

Eshop/main/views.py
from django.shortcuts import render, redirect
from . models import Category, Brand, Product, ProductAttribute, Color, Size, Baner
from django.db.models import Count, Max, Min
from django.http import JsonResponse
from django.template.loader import render_to_string

from . import views

# Create your views here.
def home(request):
    banners=Baner.objects.all().order_by('-id') 
     
    data=Product.objects.filter(is_featured=True).order_by('-id')
    
    context={'banners':banners,'data':data}
    return render(request, 'index.html',context)

def category_list(request):
    cattegories=Category.objects.all().order_by('-id')
    context={
        'cattegories':cattegories
    }
    return render(request, 'categories.html',context)
def brand_list(request):
     #brands that have products with valid product attribute images.
     brands = Brand.objects.filter(product__productattribute__image__isnull=False).distinct()
     context={
        'brands':brands
    }
     return render(request, 'brand.html',context)

def product_list(request):
    products=Product.objects.all().order_by('-id')
    #pass to to context processor
    max_price=ProductAttribute.objects.aggregate(Max('price'))
    min_price=ProductAttribute.objects.aggregate(Min('price'))

    context={
        'products':products,
        'max_price':max_price,
        'min_price':min_price
    }
    return render(request, 'product.html',context)

def category_product_list(request, cat_id):
    category=Category.objects.get(id=cat_id)
    products=Product.objects.filter(category=category).order_by('-id')
    #pass to to context processor
    context={'products':products}
    return render(request,'category_product_list.html',context)


def brand_product_list(request, brand_id):
    brand=Brand.objects.get(id=brand_id)
    products=Product.objects.filter(brand=brand).order_by('-id')
    #pass to to context processor
    context={'products':products}
    return render(request,'brand_product_list.html',context)

def product_detail(request, slug, id):
    product = Product.objects.get(id=id)
    product_attributes = product.productattribute_set.all()
    colors=product_attributes.values('color__color_code','color__title').distinct()
    
    related_products = Product.objects.filter(category=product.category).exclude(id=id)[:4]
    context = {
        'product': product,
        'product_attributes': product_attributes,
        'colors':colors,
        'related_products': related_products 
    }
    return render(request, 'product_detail.html', context)

def search(request):
    #q is the name of the input field in the search form in the base.html
    q=request.GET['q'] 
    data=Product.objects.filter(title__icontains=q).order_by('-id')
    
    context={'data':data}
    return render(request, 'search.html',context)


def filter_data(request):
    colors = request.GET.getlist('color[]') # 'color[] if came from filter.html , similar rest of category , brand size
    categories = request.GET.getlist('category[]')
    brands = request.GET.getlist('brand[]')
    sizes = request.GET.getlist('size[]')

    allproducts = Product.objects.all()

    # Apply filters if selected
    if len(colors)>0:
        allproducts = allproducts.filter(productattribute__color__id__in=colors).distinct()
    if categories:
        allproducts = allproducts.filter(category__id__in=categories).distinct()
    if brands:
        allproducts = allproducts.filter(brand__id__in=brands).distinct()
    if sizes:
        allproducts = allproducts.filter(productattribute__size__id__in=sizes).distinct()

    t = render_to_string('ajax/product-list.html', {'products': allproducts})

    return JsonResponse({'data': t})

    

Eshop/templates/ajax/product-list.html
{% for product in products %}
<div class="col-lg-4 col-md-6 mb-4 product-box">
	<div class="card shadow">
	  <a href="{% url 'product_detailPage' product.slug product.id %}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
	  <div class="card-body">
	    <h5 class="card-text"><a href="{% url 'product_detailPage' product.slug product.id %}">{{product.title}}</a></h5>
	    <h6>$ {{product.productattribute_set.first.price}}</h6>
	  </div>
	  <div class="card-footer">
	  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
	  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
	  	<span class="float-right">
	  		4.5/5
	  		<i class="fa fa-star text-warning"></i>
	  	</span>
	  </div>
	</div>
</div>
{% endfor %}
			

Eshop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Ecommerce Bootstrap Template</title>
	<!-- Font Awesome -->
	<link rel="stylesheet" type="text/css" href="{% static 'fontawesome-free/css/all.min.css' %}" />
	<!-- Bootstrap 4 CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'bs4/bootstrap.min.css' %}" />
	<!-- Main Jquery -->
	<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
	<!-- Bootstrap 4 JS -->
	<script type="text/javascript" src="{% static 'bs4/bootstrap.min.js' %}"></script>
    <link rel="icon" href="{% static 'favicon.ico' %}">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
		<div class="container">
		  <a class="navbar-brand" href="#">Bottle Shop</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">

        <form class="form-inline my-2 my-lg-0" action="/search">
          <div class="input-group ">

            <input name="q" type="text" class="form-control" placeholder="search"/>
            <div class="input-group-append">
              <button class="btn btn-dark" type="submit" id="button-addon2">Search</button>
            </div>
            
          </div>
        </form>

		    <ul class="navbar-nav ml-auto">
		      <li class="nav-item">
		        <a class="nav-link text-white" href="{% url 'homePage' %}">Home</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="{% url 'category_listPage' %}">Categories</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="{% url 'brand_listPage' %}">Brands</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="#"><i class="fa fa-shopping-cart"></i> Cart (2)</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="#"><i class="fa fa-user"></i> My Account</a>
		      </li>
		    </ul>
		  </div>
		</div>
	</nav>

    {% block content %}

    {% endblock %}


    <!-- Footer -->
    <footer class="pt-4 my-md-5 pt-md-5 border-top container">
        <div class="row">
          <div class="col-12 col-md">
            <a href="#">Bottle Shop</a>
            <small class="d-block mb-3 text-muted">&copy; 2017-2020</small>
          </div>
          <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Cool stuff</a></li>
              <li><a class="text-muted" href="#">Random feature</a></li>
              <li><a class="text-muted" href="#">Team feature</a></li>
              <li><a class="text-muted" href="#">Stuff for developers</a></li>
              <li><a class="text-muted" href="#">Another one</a></li>
              <li><a class="text-muted" href="#">Last time</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Resource</a></li>
              <li><a class="text-muted" href="#">Resource name</a></li>
              <li><a class="text-muted" href="#">Another resource</a></li>
              <li><a class="text-muted" href="#">Final resource</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Team</a></li>
              <li><a class="text-muted" href="#">Locations</a></li>
              <li><a class="text-muted" href="#">Privacy</a></li>
              <li><a class="text-muted" href="#">Terms</a></li>
            </ul>
          </div>
        </div>
      </footer>
    </body>
    </html>

Eshop/templates/brand.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Brands</h3>
	<div class="row">
		{% if brands %}
		{% for brand in brands %}
			<div class="col-md-3 mb-4">
				<div class="card shadow">
					<a href="{% url 'brand_product_listPage' brand.id %}">
						{% if brand.product_set.first and brand.product_set.first.productattribute_set.first and brand.product_set.first.productattribute_set.first.image %}
							<img src="{{ brand.product_set.first.productattribute_set.first.image.url }}" class="card-img-top" alt="{{ brand.title }}">
						{% else %}
							<img src="/static/default.jpg" class="card-img-top" alt="No Image Available">
						{% endif %}
					</a>
					<div class="card-body">
						<h6 class="card-text"><a href="{% url 'brand_product_listPage' brand.id %}">{{ brand.title }}</a></h6>
					</div>
				</div>
			</div>
		{% endfor %}
	{% endif %}
	
		
	</div>
</main>
{% endblock %}

Eshop/templates/brand_product_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filter.html' %}
			
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row">
                {% for product in products %}
				<div class="col-md-4 mb-4">
					<div class="card shadow">
					  <a href="{% url 'product_detailPage' product.slug product.id %}">
						<!-- Add the 'img-fluid' class to make the image responsive -->
						<img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top img-fluid" alt="{{product.title}}">
					  </a>
					  <div class="card-body">
						<h5 class="card-text"><a href="{% url 'product_detailPage' product.slug product.id %}"> {{product.title}}</a></h5>
					  </div>
					  <div class="card-footer">
						<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
						<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
						<span class="float-right">
						  4.5/5
						  <i class="fa fa-star text-warning"></i>
						</span>
					  </div>
					</div>
				  </div>
				  
                {% endfor %}
				
			</div>
			<p class="my-4 text-center"><a href="/products.php" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync"></i></a></p>
		</div>
	</div>
</main>

{% endblock %}

Eshop/templates/categories.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Categories</h3>
	<div class="row">
        {% if cattegories %}
        {% for category in cattegories %}
		
		<div class="col-md-3 mb-4">
            
			<div class="card shadow">
			  <a href="{% url 'category_product_listPage' category.id %}"><img src="/media/{{category.image}}" class="card-img-top"></a>
			  <div class="card-body">
			    <h6 class="card-text"><a href="{% url 'category_product_listPage' category.id %}">{{category.title}}  </a></h6>
			  </div>
			</div>
          
		</div>
		{% endfor %}
		{% endif %}
	</div>
	
</main>
{% endblock %}

Eshop/templates/category_product_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filter.html' %}
	
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row">
                {% for product in products %}
				<div class="col-md-4 mb-4">
					<div class="card shadow">
					  <a href="{% url 'product_detailPage' product.slug product.id %}">
						<!-- Add the 'img-fluid' class to make the image responsive -->
						<img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top img-fluid" alt="{{product.title}}">
					  </a>
					  <div class="card-body">
						<h5 class="card-text"><a href="{% url 'product_detailPage' product.slug product.id %}"> {{product.title}}</a></h5>
					  </div>
					  <div class="card-footer">
						<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
						<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
						<span class="float-right">
						  4.5/5
						  <i class="fa fa-star text-warning"></i>
						</span>
					  </div>
					</div>
				  </div>
				  
                {% endfor %}
				
			</div>
			<p class="my-4 text-center"><a href="/products.php" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync"></i></a></p>
		</div>
	</div>
</main>

{% endblock %}

Eshop/templates/filter.html
{% load static %}
<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
<!-- Now load the product filter script -->
<script type="text/javascript" src="{% static 'product-filter.js' %}"></script>

<h3 class="mb-4 border-bottom pb-1">Filters</h3>
<!-- Price Filter -->
<div class="card mb-4">
	<h6 class="card-header">Price</h6>
	<div class="list-group list-group-flush">
		<li class="list-group-item">
			<input type="range" value="{{minMaxPrice.price__min}}" max={{minMaxPrice.price__max}} min={{minMaxPrice.price__min}} id="rangeInput" oninput="maxPrice.value=this.value" />
			<p>{{minMaxPrice.price__min}}-{{minMaxPrice.price__max}}</p>
		</li>
		<li class="list-group-item">
			Max: <input type="number" value="{{minMaxPrice.price__min}}" max={{minMaxPrice.price__max}} min={{minMaxPrice.price__min}} class="form-control" id="maxPrice" onkeyup="rangeInput.value=this.value" id="maxPrice" />
			<button id="priceFilterBtn" class="btn btn-info btn-sm mt-1">Filter</button>
		</li>
	</div>
</div>


			<!-- Filter 1 -->
			<div class="card mb-4">
				<h6 class="card-header">Colors</h6>
				<div class="list-group list-group-flush">
					{% for c in clr %}
					<li class="list-group-item">
						<input class="filter-checkbox" data-filter="color" name="color[]"  value="{{c.color__id}}" type="checkbox" />&nbsp;
						<button class="btn" style="background-color: {{ c.color__color_code }} "></button>
					</li>
				{% endfor %}
				</div>
			</div>
			<!-- Filter 2 -->
			<div class="card mb-4">
				<h6 class="card-header">Categories</h6>
				<div class="list-group list-group-flush">
                    {% for cat in cats %}
					<li class="list-group-item">
						<input class="filter-checkbox" name="category[]" data-filter="category" value="{{cat.category__id}}"  type="checkbox" />&nbsp;
						{{cat.category__title}}
					</li>
                    {% endfor %}
				</div>
			</div>
			<!-- Filter 3 -->
			<div class="card mb-4">
				<h6 class="card-header">Brands</h6>
				<div class="list-group list-group-flush">
                    {% for brand in brands %}
					<li class="list-group-item">
						<input class="filter-checkbox" value="{{brand.brand__id}}" data-filter="brand" name="brand[]" type="checkbox" />&nbsp;
						{{brand.brand__title}}
					</li>
                    {% endfor %}
					
				</div>
			</div>
			<!-- Filter 3 -->
			<div class="card mb-4">
				<h6 class="card-header">Sizes</h6>
				<div class="list-group list-group-flush">
					 {% for size in sizeset %}
					<li class="list-group-item">
						<input class="filter-checkbox"  name="size[]" data-filter="size" value="{{size.size__id}}" type="checkbox" />&nbsp;
						{{size.size__title}}
					</li>
                    {% endfor %}
				</div>
			</div>

			
		

Eshop/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Home Slider -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    {% for banner in banners %}
    {% if forloop.counter == 1 %}
    <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}" class="active"></li>
    {% else %}
    <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}" ></li>
    {% endif %}
    {% endfor %}
  </ol>
  <div class="carousel-inner">
      {% for banner in banners %}
      {% if forloop.counter == 1 %}
    <div class="carousel-item active">
      {% else %}
    <div class="carousel-item">
      {% endif %}
      <img src="/media/{{banner.img}}"  class="d-block w-100" alt="...">
    </div>
    {% endfor %}
    
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>

<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Featured Products</h3>
	<div class="row">
    {% for featured in data %}
		
		<div class="col-md-3 mb-4">
			<div class="card shadow">
			  <a href="{% url 'product_detailPage' featured.slug featured.id %}"><img src="/media/{{featured.productattribute_set.first.image }}" class="card-img-top" alt="{{featured.title}}"></a>
			  <div class="card-body">
			    <h6 class="card-text"><a href="{% url 'product_detailPage' featured.slug featured.id %}">{{featured.title}} </a></h6>
			  </div>
			  <div class="card-footer">
			  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
			  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
			  	<span class="float-right">
			  		4.5/5
			  		<i class="fa fa-star text-warning"></i>
			  	</span>
			  </div>
			</div>
		</div>
        {% endfor %}
		
	</div>
	<p class="my-4 text-center"><a href="{% url 'product_listPage' %}" class="btn btn-dark btn-sm">All Products <i class="fa fa-long-arrow-alt-right"></i></a></p>
</main>
{% endblock %}

Eshop/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filter.html' %}

		</div>
			
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row" id="filteredProducts">
				<p class="ajx-loader">Loading...</p>

                {% for product in products %}
				<div class="col-md-4 mb-4">
					<div class="card shadow">
					  <a href="{% url 'product_detailPage' product.slug product.id %}">
						<!-- Add the 'img-fluid' class to make the image responsive -->
						 <!-- for reverse relation ship used : productattribute_set-->
						<img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top img-fluid" alt="{{product.title}}">
					  </a>
					  <div class="card-body">
						<h5 class="card-text"><a href="{% url 'product_detailPage' product.slug product.id %}"> {{product.title}}</a></h5>
					  </div>
					  <div class="card-footer">
						<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
						<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
						<span class="float-right">
						  4.5/5
						  <i class="fa fa-star text-warning"></i>
						</span>
					  </div>
					</div>
				  </div>
				  
                {% endfor %}
				
			</div>
			<p class="my-4 text-center"><a href="/products.php" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync"></i></a></p>
		</div>
	</div>
	</div>
</main>

{% endblock %}

Eshop/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1"> <span> search result for </span> {{request.GET.q}}</h3>
	<div class="row">
    {% for featured in data %}
		
		<div class="col-md-3 mb-4">
			<div class="card shadow">
			  <a href="{% url 'product_detailPage' featured.slug featured.id %}"><img src="/media/{{featured.productattribute_set.first.image }}" class="card-img-top" alt="{{featured.title}}"></a>
			  <div class="card-body">
			    <h6 class="card-text"><a href="{% url 'product_detailPage' featured.slug featured.id %}">{{featured.title}} </a></h6>
			  </div>
			  <div class="card-footer">
			  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
			  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
			  	<span class="float-right">
			  		4.5/5
			  		<i class="fa fa-star text-warning"></i>
			  	</span>
			  </div>
			</div>
		</div>
        {% endfor %}
	</div>
	
</main>
{% endblock %}